# Generated by Django 4.2.3 on 2023-09-06 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller_tbl',
            name='password',
        ),
        migrations.RemoveField(
            model_name='staff_tbl',
            name='password',
        ),
        migrations.RemoveField(
            model_name='user_tbl',
            name='password',
        ),
    ]
