# Generated by Django 4.2.3 on 2023-09-09 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_seller_tbl_password_remove_staff_tbl_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller_tbl',
            name='age',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
